Til 66
argon1025/TILog-server pull request #44
Opened 2021-09-12 13:40 UTC by MINJE-98

필요한 모듈 설치 및 적용

2021-09-13 13:19 UTC, Daphne-dev approved these changes
확인했습니다.

2021-09-13 15:41 UTC, argon1025 requested changes
다음과같이 변경 또는 개선하면 좋을것 같습니다.

2021-09-13 15:41 UTC, argon1025 commented on src/src/main.ts
> +  });
CORS 환경변수로 methods 정의할 수 있게 해주면 좋을꺼같습니다

2021-09-13 15:41 UTC, argon1025 commented on src/src/main.ts
> +  client.on('error', (error) => console.log('Redis Connect error:' + error));
NestJS Logger.error 변경
이후 throw Error로 서버 시작 안되도록

2021-09-13 15:41 UTC, argon1025 commented on src/src/main.ts
> +      store: new redisStore({ client }),
환경변수화

2021-09-15 06:41 UTC, argon1025 approved these changes

2021-09-15 08:05 UTC, merged